stages:
  - lint
  - test

image: python:3.10

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

flake8:
  stage: lint
  script:
    - flake8 .

black:
  stage: lint
  script:
    - black --check .

isort:
  stage: lint
  script:
    - isort . --check-only

mypy:
  stage: lint
  script:
    - mypy project --explicit-package-bases

pytest:
  stage: test
  script:
    - pytest -v project
